---
- hosts: all
  become: yes
  tasks:

    - name: validate if MySQL is installed
      ansible.builtin.command: "rpm -q mysql-server"
      register: mysql_check
      ignore_errors: yes

    - name: MySQL is not installed, skipping patching
      ansible.builtin.debug:
        msg: "MySQL is not installed on this host. Skipping patching."
      when: mysql_check.rc != 0

    - name: Get MySQL version information
      community.mysql.mysql_info:
        filter: version
        login_user: root
        login_password: "{{ mysql_root_password }}"
        # Use the socket to avoid "protocol mismatch" errors
        login_unix_socket: /var/lib/mysql/mysql.sock 
      register: mysql_server_info   
    - name: Debug MySQL version information
      ansible.builtin.debug:
        msg: "MySQL version: {{ mysql_server_info.version.full }}"

    - name: Download MySQL 8.4 repo for RHEL 9
      ansible.builtin.uri:
        url: "https://repo.mysql.com/mysql84-community-release-el9-3.noarch.rpm"
        dest: "/tmp/mysql84-community-release-el9-3.noarch.rpm"
        headers:
          User-Agent: "Mozilla/5.0"
        status_code: 200

    - name: Update the DNF package cache
      ansible.builtin.dnf:
        update_cache: yes

  #   - name: Update MySQL packages
  #     ansible.builtin.dnf:
  #       name: mysql-server
  #       state: present
  #     notify:
  #       - Restart MySQL

  # handlers:
  #   - name: Restart MySQL
  #     service:
  #       name: mysql
  #       state: restarted